### ISSUE TITLE
setRotation() has limited feature. data is flipped instead of printing in right corner.

### ISSUE THREAD

**Issue by engrziarehman** [mongoose-os-libs/ili9341-spi#13]
in original [adafruit](https://github.com/adafruit/Adafruit_ILI9341) library there is a setRotation() that takes input from 0-3 to start printing from each corner of the lcd, without flipping the data. but here in this library, setRotation() also take 0-3 inputs but only 0-1 are printing straight while 2-3 inputs are printing flipped data, not the straight as were in original library. 

I was using setRotation(3) in [adafruit](https://github.com/adafruit/Adafruit_ILI9341) library to start printing from last corner of the lcd, but here the data is flipped and i am unable to set rotation correctly.

**Comment by tripflex** [comment]
I'm having this problem as well, can confirm this 👍  ... which 2-3 are `PORTRAIT_FLIP` and `LANDSCAPE_FLIP` where in my case, this causes the text to show as RTL (right to left) instead of normal flip

**Comment by tripflex** [comment]
@engrziarehman so here's how I fixed this until the maintainer of this repo can respond ... first you have to build locally (requires docker installed):
```shell
 mos build --platform esp32 --local --verbose
```

Then inside your project you will see a directory named `deps` .. inside that dir look for `ili9341-spi` and open `/deps/ili9341-spi/src/mgos_ili9341.c`

Around line 28 I added these defines:
```c
#define MADCTL_MY  0x80     ///< Bottom to top
#define MADCTL_MX  0x40     ///< Right to left
#define MADCTL_MV  0x20     ///< Reverse Mode
#define MADCTL_ML  0x10     ///< LCD refresh Bottom to top
#define MADCTL_RGB 0x00     ///< Red-Green-Blue pixel order
#define MADCTL_BGR 0x08     ///< Blue-Green-Red pixel order
#define MADCTL_MH  0x04     ///< LCD refresh right to left
```

Then on line #158 comment out or replace this code `madctl |= 1 << 5;`

And add this code:
```c
madctl = (MADCTL_MX | MADCTL_MY | MADCTL_MV | MADCTL_BGR);
```

Then run another local build, and it will build with your customizations on that library (instead of pulling from git), and voila, profit!

This is exactly the same method used by the Adafruit lib:
https://github.com/adafruit/Adafruit_ILI9341/blob/master/Adafruit_ILI9341.cpp#L481

As well as the ESP32 TFT display lib:
https://github.com/loboris/ESP32_TFT_library/blob/aa21772f54a71887ec08b2e8bbaef9e304009891/components/tft/tftspi.c#L845

**Comment by tripflex** [comment]
For now you could also just set the lib to my github repo until this can be addressed in this repo (if you don't want to manually build and modify)

```yml
libs:
  - origin: https://github.com/tripflex/ili9341-spi
```

**Comment by pimvanpelt** [comment]
You're right, @tripflex and thanks for pointing out the bug :)
Looking at the two references you cited, it's clear that I'm mirroring not flipping the display. Fix incoming shortly.

**Comment by engrziarehman** [comment]
@tripflex  @pimvanpelt  thankyou :)
